version: '3.8'

services:
  app:
    build: .
    ports:
      - '3333:3333'
    volumes:
      - .:/app
    environment:
      - NODE_ENV=production
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: bat
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  postgres_data:
